### ISSUE TITLE
User-agent not set in headers, logs show python-requests/2.22.0

### ISSUE THREAD

**Issue by meewash-p** [MartinIngesen/MSOLSpray#3]
Script does not set custom User-agent for the requests. As a result, AAD sign-ins log shows default python-requests user-agent which in case of penetration testing can raise suspicion if decent SIEM rules are in place.

Current code (lines 7-74)
```
    headers = {

        'Accept': 'application/json',

        'Content-Type': 'application/x-www-form-urlencoded',

    }
```

Changed User-agent (example):

``` 
    headers = {

        'Accept': 'application/json',

        'Content-Type': 'application/x-www-form-urlencoded',

        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36'

    }
```

**Comment by MartinIngesen** [comment]
I agree. I am open to a PR that would add this op-sec enhancement, but I will close this as I do not consider it to be an "issue" in and of itself.
